/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as appLoginRouteImport } from './routes/(app)/login'
import { Route as appCoursesIndexRouteImport } from './routes/(app)/courses/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as appCoursesCourseIdRouteImport } from './routes/(app)/courses/$courseId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const appLoginRoute = appLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => appRouteRoute,
} as any)
const appCoursesIndexRoute = appCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const appCoursesCourseIdRoute = appCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof appLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/login': typeof ApiLoginRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/$courseId': typeof appCoursesCourseIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/courses': typeof appCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof appLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/login': typeof ApiLoginRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/': typeof appIndexRoute
  '/admin': typeof AdminIndexRoute
  '/courses/$courseId': typeof appCoursesCourseIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/courses': typeof appCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(app)/login': typeof appLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/login': typeof ApiLoginRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(app)/courses/$courseId': typeof appCoursesCourseIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/(app)/courses/': typeof appCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/admin/users'
    | '/api/login'
    | '/api/register'
    | '/api/users'
    | '/'
    | '/admin/'
    | '/courses/$courseId'
    | '/api/users/$id'
    | '/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin/users'
    | '/api/login'
    | '/api/register'
    | '/api/users'
    | '/'
    | '/admin'
    | '/courses/$courseId'
    | '/api/users/$id'
    | '/courses'
  id:
    | '__root__'
    | '/(app)'
    | '/admin'
    | '/(app)/login'
    | '/admin/users'
    | '/api/login'
    | '/api/register'
    | '/api/users'
    | '/(app)/'
    | '/admin/'
    | '/(app)/courses/$courseId'
    | '/api/users/$id'
    | '/(app)/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiLoginRoute: typeof ApiLoginRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(app)/login': {
      id: '/(app)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appLoginRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/courses/': {
      id: '/(app)/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof appCoursesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/(app)/courses/$courseId': {
      id: '/(app)/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof appCoursesCourseIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appLoginRoute: typeof appLoginRoute
  appIndexRoute: typeof appIndexRoute
  appCoursesCourseIdRoute: typeof appCoursesCourseIdRoute
  appCoursesIndexRoute: typeof appCoursesIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appLoginRoute: appLoginRoute,
  appIndexRoute: appIndexRoute,
  appCoursesCourseIdRoute: appCoursesCourseIdRoute,
  appCoursesIndexRoute: appCoursesIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiLoginRoute: ApiLoginRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
