/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appRegisterRouteImport } from './routes/(app)/register'
import { Route as appLoginRouteImport } from './routes/(app)/login'
import { Route as appCoursesIndexRouteImport } from './routes/(app)/courses/index'
import { Route as appCoursesCourseIdRouteImport } from './routes/(app)/courses/$courseId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appRegisterRoute = appRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => appRouteRoute,
} as any)
const appLoginRoute = appLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => appRouteRoute,
} as any)
const appCoursesIndexRoute = appCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCoursesCourseIdRoute = appCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof appLoginRoute
  '/register': typeof appRegisterRoute
  '/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/$courseId': typeof appCoursesCourseIdRoute
  '/courses': typeof appCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof appLoginRoute
  '/register': typeof appRegisterRoute
  '/': typeof appIndexRoute
  '/admin': typeof AdminIndexRoute
  '/courses/$courseId': typeof appCoursesCourseIdRoute
  '/courses': typeof appCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(app)/login': typeof appLoginRoute
  '/(app)/register': typeof appRegisterRoute
  '/(app)/': typeof appIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(app)/courses/$courseId': typeof appCoursesCourseIdRoute
  '/(app)/courses/': typeof appCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/register'
    | '/'
    | '/admin/'
    | '/courses/$courseId'
    | '/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/admin'
    | '/courses/$courseId'
    | '/courses'
  id:
    | '__root__'
    | '/(app)'
    | '/admin'
    | '/(app)/login'
    | '/(app)/register'
    | '/(app)/'
    | '/admin/'
    | '/(app)/courses/$courseId'
    | '/(app)/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/register': {
      id: '/(app)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof appRegisterRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/login': {
      id: '/(app)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appLoginRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/courses/': {
      id: '/(app)/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof appCoursesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/courses/$courseId': {
      id: '/(app)/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof appCoursesCourseIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appLoginRoute: typeof appLoginRoute
  appRegisterRoute: typeof appRegisterRoute
  appIndexRoute: typeof appIndexRoute
  appCoursesCourseIdRoute: typeof appCoursesCourseIdRoute
  appCoursesIndexRoute: typeof appCoursesIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appLoginRoute: appLoginRoute,
  appRegisterRoute: appRegisterRoute,
  appIndexRoute: appIndexRoute,
  appCoursesCourseIdRoute: appCoursesCourseIdRoute,
  appCoursesIndexRoute: appCoursesIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
